sudo: required
dist: xenial

language: python

python:
  - "3.7"
  
services:
   - docker

before_install:
  - docker run -d --name kb -p 7474:7474 -p 7687:7687 --env=NEO4J_AUTH=none --env=NEO4J_dbms_read__only=false --env=NEO4J_dbms_memory_heap_maxSize=1G --volume=$TRAVIS_BUILD_DIR/src/:/import/ virtualflybrain/docker-neo4j-knowledgebase
  - sleep 50s
  - echo -e "Checking local KB connection"
  - curl -sSf -u neo4j:neo4j "http://localhost:7474/db/data/"
  - git clone https://github.com/VirtualFlyBrain/VFB_neo4j.git
  - export PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/VFB_neo4j/src/
  
install:
  - pip install -r requirements.txt

script:
  - cd src
#  - test_working.py
#  - test_submission.py
