sudo: required
dist: xenial

language: python

python:
  - "3.7"
  
services:
   - docker

before_install:
  - docker run -d --name kb -p 7474:7474 -p 7687:7687 --env=NEO4J_AUTH=none --env=NEO4J_dbms_read__only=false --env=NEO4J_dbms_memory_heap_maxSize=1G --volume=$TRAVIS_BUILD_DIR/src/:/import/ virtualflybrain/docker-neo4j-knowledgebase
  - sleep 50s
  - echo -e "travis_fold:start:Checking_local_KB_connection" || true
  - docker logs kb
  - curl -sSf -u neo4j:neo4j "http://localhost:7474/db/data/" 
  - echo -e "travis_fold:end:Checking_local_KB_connection" || true
  - git clone https://github.com/VirtualFlyBrain/VFB_neo4j.git
  - export PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/VFB_neo4j/src/
  - pwd
  - export BUILD_TYPE=`if [[ "$TRAVIS_BRANCH" == *"_curation" ]]; then echo "curation"; elif [ "$TRAVIS_BRANCH" == "master" ]; then echo "master"; else echo "other"; fi`
  - export BASEPATH=`if [ "$BUILD_TYPE" == "curation" ]; then echo "../records"; else echo "vfb/curation/test/resources/records"; fi`
  
install:
  - pip install -r requirements.txt
  - pip install -r VFB_neo4j/requirements.txt
  - pip install ruamel.yaml # Hack for different package name on pip vs condaForge

script:
  - cd src
  - python -m vfb.curation.test.test_peevish
  - if [ ! "$BUILD_TYPE" == "curation" ]; python run_peevish.py --test_mode --base_path=$BASEPATH http://localhost:7474 neo4j neo4j; fi
  - python run_peevish.py --base_path=$BASEPATH http://localhost:7474 neo4j neo4j

