$schema: "http://json-schema.org/draft-04/schema#"
title: VFB_cur_meta
type: object
additionalProperties: False
required: ['description', 'compulsory', 'type']
properties:
  yaml: Boolean
  compulsory: Boolean
  multiple: Boolean
  description: String
  type:
    enum['Property', 'Class', 'Ind', 'Property_id', 'Ind_id, 'Class_id', 'String', 'Integer', 'float']

   
    
  
